### ISSUE TITLE
the problem of seg_loss

### ISSUE THREAD

**Issue by duxiangcheng** [MichalBusta/E2E-MLT#67] opened 2020-04-02 08:21 UTC
I'm confused that the seg_loss function is always negative? Why does this happen? @MichalBusta 
![捕获](https://user-images.githubusercontent.com/20560934/78226204-f25dc180-74fd-11ea-8935-a1c78864abfb.JPG)

**Comment by MichalBusta** [comment] 2020-04-02 09:03
Duplicate of #29

**Closed** 2020-05-01 09:51 UTC
